config/routes.rb
Incon::Application.routes.draw do
  

  devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :project_managers 
  resources :applications

  

  
  match '/applications/:id/' => 'applications#create', :as => '_application'
  get '/applications/:id/edit' => 'applications#edit', :as => 'edit_application'

   root :to => 'project_managers#new'

end

app/models/project_manager.rb
class ProjectManager 
include Mongoid::Document
include Mongoid::Timestamps::Created

  field :project_name, :type => String
  #references_many :application

attr_accessible :project_name, :applications_attributes

#Validations
validates :project_name, :presence => true

#Associations
has_many :applications, :dependent => :destroy

accepts_nested_attributes_for :applications

# def self.search(search)
# 	 if search	 	
# 	    find(:all, :conditions => ['project_name LIKE ? or applications.application_name LIKE ? ', "%#{search}%", "%#{search}%"], :include => [:applications])
# 	  else
# 	    find(:all)
# 	  end
#   end



end

app/controllers/project_managers_controller.rb
class ProjectManagersController < ApplicationController
  # GET /project_managers
  # GET /project_managers.json
  before_filter :authenticate_user!

  
  def index
    @project_managers = ProjectManager.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_managers }
    end
  end

  # GET /project_managers/1
  # GET /project_managers/1.json
  def show
    @project_manager = ProjectManager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_manager }
    end
  end

  # GET /project_managers/new
  # GET /project_managers/new.json
  def new

    @project_manager = ProjectManager.new
    @project_manager.applications.build

   # @project_managers = ProjectManager.search(params[:search]).paginate(:per_page => 2, :page => params[:page])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_manager }
    end
  end

  # GET /project_managers/1/edit
  def edit
    @application = Application.find_by_id(params[:id])
  end

  # POST /project_managers
  # POST /project_managers.json
  def create
    @project_manager = ProjectManager.new(params[:project_manager])

    respond_to do |format|
      if @project_manager.save
        format.html { redirect_to action: "new", notice: 'Project manager was successfully created.' }
        format.json { render json: @project_manager, status: :created, location: @project_manager }
      else
        format.html { render action: "new", notice: 'Project manager was successfully created.' }
        format.json { render json: @project_manager.errors, status: :unprocessable_entity  }
      end
    end
  end

  # PUT /project_managers/1
  # PUT /project_managers/1.json
  def update
    @project_manager = ProjectManager.find(params[:id])
    @application = Application.find_by_id(params[:id])

    respond_to do |format|
      if @project_manager.update_attributes(params[:project_manager])
        format.html { redirect_to @project_manager, notice: 'Project manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_managers/1
  # DELETE /project_managers/1.json
  def destroy
    @project_manager = ProjectManager.find(params[:id])
    @project_manager.destroy

    respond_to do |format|
      format.html { redirect_to action: "new" }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_managers_helper.rb
module ProjectManagersHelper
end

app/views/project_managers/_details.html.erb
<table>
  <tr>
    <th>Project Name</th>
    <th>App Name</th>
    <th></th>
    <th></th>
  </tr>

 <%= @projects.each do |project_manager| %>
<% project_manager.applications.each do |t| %>

  <tr>
    <td><%= project_manager.project_name %></td>

   <td><%=  t.application_name %></td>
     
 <%# end %>   
    <td><%= link_to 'Show', project_manager %></td>
    <td><%= link_to 'Edit', edit_project_manager_path(project_manager) %></td>
    <td><%= link_to 'Destroy', project_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
  
</table>

<br />

<%= link_to 'New Project manager', new_project_manager_path %>

app/views/project_managers/_form.html.erb
   
   	<%= simple_form_for @project_manager do |f| %>
 		<%= f.input :project_name, :hint=>"Project Name cannot be changed, Max of 10 Characters" %>
	 <%= f.fields_for :applications do |builder| %>
	 	<%= builder.input :application_name, :hint=>"Application Name can be changed, Max of 15 Characters" %>
	 <% end %>
	 <div class = "button-app">
 		<%= f.submit "Create App" %>
 	</div>
	<% end %>

 

app/views/project_managers/_list.html.erb
<h2 class="Title3">Your Apps</h2>

 <div>

    <%= form_tag project_managers_path, :method => 'get' do %>     
    <p>        
    <%#= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search", :name => nil %>    
   </p>
   <% end %>
</div>

<div class="Table">
<table class="hovertable">

<% @project_managers.each do |project_manager| %>
  
    <div class="row-fluid">
    
    <%#= link_to image_tag()%> 

    
    <% for application in @project_manager.applications %>
    <% project_manager.applications.each do |t| %>
    <td></td>
    <td>ID ::<%= project_manager.id %> </td>
     <td>Application Name:: <%=  t.application_name %></td>
     <tr></tr>
     <% end %>
    <% end %></br>
     
     <td>Project Name:: <%= project_manager.project_name %></td></br> 
      <div class="data-actions" >
     <td>App Created On:: <%= project_manager.created_at.strftime('%d/%m/%Y') %> </td>
     
     <td><%= link_to raw("<i class='icon-edit'></i> Edit"), edit_application_path(:id => project_manager.applications.first.id) %> <!-- Has Many --> |
     <%= link_to raw("<i class='icon-trash'></i> Delete"), project_manager, method: :delete, :data => { :confirm => "Are you sure you want to delete ?" } %> |
     <%= link_to raw("<i class='icon-ok-sign'></i> Publish") %> |
     <%#= link_to raw("<i class='icon-download'> </i> Clone") %> 
     <%= link_to raw("<i class='icon-tasks'></i> Test") %> </br></td>
    </div>
    <% end %>
    </table></br>
    
    
</div> </br>
    <div class="pagination">
       <%= will_paginate @project_managers %>
    </div>

app/views/project_managers/edit.html.erb
<h2 class="Title4">Application Settings</h2>
<%= render '/applications/form' %>

app/views/project_managers/index.html.erb
<h1>Listing project_managers</h1>

<table>
  <tr>
    <th>Project Name</th>
    <th>App Name</th>
    <th></th>
    <th></th>
  </tr>

 <% @project_managers.each do |project_manager| %>
<% project_manager.applications.each do |t| %>

  <tr>
    <td><%= project_manager.project_name %></td>

   <td><%=  t.application_name %></td>
     
 <%# end %>   
    <td><%= link_to raw("<i class='icon-edit'></i> Edit"), edit_application_path(:id => project_manager.applications.first.id) %><%#= link_to 'Show', project_manager %></td>
    <td><%#= link_to 'Edit', edit_project_manager_path(project_manager) %></td>
    <td><%#= link_to 'Destroy', project_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
  
</table>

<br />

<%= link_to 'New Project manager', new_project_manager_path %>

app/views/project_managers/new.html.erb
<div class="ContentsForm">
	<div class= "content-side">
	
			<p> To start building your App, please start by giving a project name.The project name is a unique identifier that helps keep track of all our assets of the Application. You would also have to define the App name here, this name can be changed at any time.</p>

	</div>

	<%= render 'form' %>
	
	
	<%= render 'list' %>
</div>

app/views/project_managers/show.html.erb
<%=  @jdata%>

<!-- <p id="notice"><%= notice %></p>

<p>
  <b>Project name:</b>
  <%= @project_manager.project_name %>
</p>



<%#= link_to 'Edit', edit_project_manager_path(@project_manager) %> |
<%#= link_to 'Back', project_managers_path %> -->