config/routes.rb
Incon::Application.routes.draw do
  

  devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :project_managers 
  resources :applications

  

  
  match '/applications/:id/' => 'applications#create', :as => '_application'
  get '/applications/:id/edit' => 'applications#edit', :as => 'edit_application'

   root :to => 'project_managers#new'

end

app/models/application.rb
class Application
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :application_name, :type => String
  field :application_type, :type => String
  field :device_type, :type => String
  field :image, :type => String
  field :imagelr, :type => String
  field :photolr, :type => String
  field :photohr, :type => String
  field :orientation, :type => String
  field :style, :type => String
  field :project_manager_id, :type => Integer
  field :version, :type => Integer
  field :tab_color, :type => String
  field :navigation_color, :type => String 
  # referenced_in :project_manager

  attr_accessible :application_name, :project_manager_id, :device_type, :tab_color, :navigation_color, :application_type , :version, :image, :style, :orientation, :imagelr, :photolr, :photohr
  attr_writer :current_step
  #validates :application_name, :presence => true

  belongs_to :project_manager, :class_name => "ProjectManager", :foreign_key => "project_manager_id"
  
  mount_uploader :image, ImageUploader
  mount_uploader :imagelr, ImagelrUploader
  mount_uploader :photolr, PhotolrUploader
  mount_uploader :photohr, PhotohrUploader

  #has_attached_file :attach

# def current_step
#   @current_step || steps.first
# end

# def steps
#   %w[naming setting device page]
# end

# def next_step
#   self.current_step = steps[steps.index(current_step)+1]
# end

# def previous_step
#   self.current_step = steps[steps.index(current_step)-1]
# end

# def first_step?
#   current_step == steps.first
# end

# def last_step?
#   current_step == steps.last
# end

# def all_valid?
#   steps.all? do |step|
#     self.current_step = step
#     valid?
#   end
# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    #@applications = Application.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
    @applications = Application.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new

   session[:application_params] ||= {}
  @application = Application.new(session[:application_params])
   @application.project_manager_id = params[:project_manager_id]
  @application.current_step = session[:application_step]
  end

  # GET /applications/1/edit
  # def edit
  #   @application = Application.find_by_id(params[:id])
  # end

   def edit
    @application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /applications
  # POST /applications.json
  # def create
  # session[:application_params].deep_merge!(params[:application]) if params[:application]
  # @application = Application.new(session[:application_params])
  # @application.current_step = session[:application_step]
  # if @application.valid?
  #   if params[:back_button]
  #     @application.previous_step
  #   elsif @application.last_step?
  #     @application.save if @application.all_valid?
  #   else
  #     @application.next_step
  #   end
  #   session[:application_step] = @application.current_step
  # end
  # if @application.new_record?
  #   render "new"
  # else
  #   session[:application_step] = session[:application_params] = nil
  #   flash[:notice] = "application saved!"
  #   redirect_to @application
  # end
  # end


  #  def update
  #   session[:application_params] = params[:application]
  #   #session[:application_params].deep_merge!(params[:application]) if params[:application]  
  #   @application = Application.find(params[:id])
  #   #session[:application_params].deep_merge!(params[:application]) if params[:application]
  #   @application = Application.find_by_id(params[:project_manager_id])
  #   @application.current_step = session[:application_step]
  #   if @application.valid?
  #   if params[:back_button]
  #       @application.previous_step
  # elsif @application.last_step?
  #     @application.update_attributes(params[:application]) if @application.all_valid?
  #   else
  #    @application.next_step 
  #  end
  #   session[:application_step] = @application.current_step
  # end
  #   if @application.update_attributes(params[:application])
  #     render action: "new"
  #   else
  #     session[:application_step] = session[:application_params] = nil
  #   flash[:notice] = "application saved!"
  #     redirect_to @application
  #   end
  #   end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  

end

app/views/applications/_device_step.html.erb
<div class="ContentsForm">
	<h4> App Property :: Icons and Images </h4> 
	
	Click on the required boxes to upload required imaged for your App. </br></br>
	<div id = "page-form">
	 <p>High Resolution &nbsp;| &nbsp; Low Resolution </p>
</div>

<p> Application Icon </p>
	<div id ="image-form" style="width: 352px; height: 185px;">
			&nbsp;&nbsp;&nbsp;&nbsp;
			<div id = "icon-left" >
<div class="fileupload fileupload-new" data-provides="fileupload">
<div class="fileupload-new thumbnail" style="width: 60px; height: 80px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 60px; max-height: 80px; line-height: 20px;"></div>
<div>
<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image, :type => "file" %><!-- <input type="file" /> --></span>
<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
</div>
	
 <!-- <div class="fileupload fileupload-new" data-provides="fileupload">
<div class="fileupload-new thumbnail" style="width: 50px; height: 50px;"><img src="http://www.placehold.it/50x50/EFEFEF/AAAAAA" /></div>
<div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div></br>

<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" /></span>
<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
</div> -->
<!-- <div class="fileupload fileupload-new" data-provides="fileupload">
<div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
<div>
<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" /></span>
<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
</div> -->
    <%#= f.input :attach_file_name %>
      
     <!-- <img src="/assets/phone.jpg" width="50" height="50"> &nbsp;&nbsp;&nbsp;&nbsp;<img src="/assets/phone.jpg" width="70" height="80"> -->
	 <%#= f.file_field :attach %><br>


</div>
<p> Splash Image </p>
<div id ="icon-form">
<%#= f.input :attach_file_name %>
 <img src="/assets/phone.jpg" width="100" height="150">&nbsp;&nbsp;&nbsp;&nbsp;<img src="/assets/phone.jpg" width="120" height="160">&nbsp;&nbsp;&nbsp;&nbsp;<img src="/assets/phone.jpg" width="140" height="180">
 <%#= f.file_field :attach %><br>
</div>
  </div>

<!--
      <div class="fileupload fileupload-new" data-provides="fileupload">
<div class="fileupload-new thumbnail" style="width: 50px; height: 50px;"><img src="http://www.placehold.it/50x50/EFEFEF/AAAAAA" /></div>
<div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div>
<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" /></span>
<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
</div>
-->

<!-- <div class="fileupload fileupload-new" data-provides="fileupload">
<div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
<div>
<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><input type="file" /></span>
<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
</div>
</div>-->

app/views/applications/_form.html.erb
<%= simple_form_for(@application) do |f| %>
  
  <div id="master">

    <div class="section">
     <div class="ContentsForm">
	
	<h4>App Property :: Device Selection</h4>
		<p> Choose the device type/s on which you want to run your application </p> </br>

		<div class="actionform">
		<p>Select the device on which you want to run your application</p>
			  <img src="/assets/phone.jpg" width="140" height="200">
   			   <img src="/assets/phone.jpg" width="140" height="200">
    		  <img src="/assets/phone.jpg" width="140" height="200"></br>
  			 <%= f.hidden_field :project_manager_id, :value => @application.project_manager_id %>
   			<%= f.input :device_type, :label => '', :collection => ["Phone", "Tablet", "Both"], :as => :radio, :set_default => :Phone %>
  		 </div>
	</div>
    

    </div>



    <div class="section">

      <div class="ContentsForm">
	  <h4>App Property :: Device Selection</h4>
	    <p> Choose the device type/s on which you want to run your application </p>
	  <div class ="">
	  <p>Select the device on which you want to run your application</p>
	  <%= f.input :application_name %>
	  <%= f.input :version %>
	  <h4> App Navigation Structure </h4>
	  	  <img src="/assets/phone.jpg" width="160" height="200">
	          <img src="/assets/phone.jpg" width="160" height="200">
	          <img src="/assets/phone.jpg" width="160" height="200"></br>


	    <div id="radio-btn">
	   <%= f.input :application_type, :label => '', :collection => ["Navi-Based","Tab-Based","View-Based"], :as => :radio, :set_default => "Navi-Based" %>
	 </div>
	</div>
			<div class= "sidebar">
	            Supported orientation</br></br>
	            
	          <!-- <img src="/assets/phone.jpg" width="40" height="60"></br></br>
	          <img src="/assets/phone.jpg" width="40" height="60"></br></br>
	          <img src="/assets/phone.jpg" width="40" height="60"></br></br>
	          <img src="/assets/phone.jpg" width="40" height="60"></br> -->
	          <div id="radio-vertical">
	            <%#= f.input :orientation, :label => '', :collection => ["Portrait", "Upside Down", "Landscape left", "Landscape Right"], :as => :radio, :set_default => "Portrait" %>
	          </div>
	        </div>
	        </div>
    </div>




    <div class="section">
      <div class="ContentsForm">
			<h4> App Property :: Icons and Images </h4> 
	
			Click on the required boxes to upload required imaged for your App. </br></br>
			<div id = "page-form">
				 <p>High Resolution &nbsp;| &nbsp; Low Resolution </p>
			</div>

			<p> Application Icon </p>
			<div id ="icon-form">
				<div id = "icon-left" >
			<div class="fileupload fileupload-new" data-provides="fileupload">
			<div class="fileupload-new thumbnail" style="width: 60px; height: 80px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
			<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 60px; max-height: 80px; line-height: 20px;"></div>
			<div>
			<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image, :type => "file" %></span>
			<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
				</div>
			</div>

			<div id = "icon-right" style="margin-left: 200px; margin-top: -120px;">
			<div class="fileupload fileupload-new" data-provides="fileupload">
			<div class="fileupload-new thumbnail" style="width: 60px; height: 50px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
			<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 60px; max-height: 90px; line-height: 20px;"></div>
			<div>
			<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image, :type => "file" %></span>
			<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
		</div>
		
	 </div>
	</br>

		</div>
		<p> Splash Image </p>
		<div id ="icon-form">
			<div id = "icon-left" >
			<div class="fileupload fileupload-new" data-provides="fileupload">
			<div class="fileupload-new thumbnail" style="width: 60px; height: 80px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
			<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 60px; max-height: 80px; line-height: 20px;"></div>
			<div>
			<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image, :type => "file" %><!-- <input type="file" /> --></span>
			<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
				</div>
			</div></div>

			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<div id = "icon-right" style="margin-left: 200px; margin-top: -170px;">
			<div class="fileupload fileupload-new" data-provides="fileupload">
			<div class="fileupload-new thumbnail" style="width: 80px; height: 100px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
			<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 80px; max-height: 120px; line-height: 20px;"></div>
			<div>
			<span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :photolr, :type => "file" %><!-- <input type="file" /> --></span>
			<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
		</div> </div></div>

		</div>
		  </div>
		    </div>
		</div>
		    </div>

     <div class="section">
    	<div class="ContentsForm">
		<h4>Page Style:: Tab-Based </h4>
		Using these properties one can define how the pages wood look and feel in the mobile

		<h4>Page Control :</h4>
			<%= f.input :orientation, :label => '', :collection => ["Portrait", "Upside Down", "Landscape left", "Landscape Right"], :set_default => "Portrait"%>

			<h4>Tab Property</h4>
			Tint :
			<div class="input-append color" data-color="rgb(255, 146, 180)" data-color-format="rgb" id="cp3">

			<input type="hidden"  value="" readonly="" name = "application[tab_color]"  > 
				<span class="add-on"><i style="background-color: rgb(255, 146, 180);"></i></span>
          </div>
			<div id= "sidebar-property">
			<h4>Navigation Property</h4>
			Tint : 
				<div class="input-append color" data-color="rgb(255, 146, 180)" data-color-format="rgb" id="cp3">
				<input type="hidden"  value="" readonly="" name = "application[navigation_color]" >
				<span class="add-on"><i style="background-color: rgb(255, 146, 180);"></i></span>
          </div>
			<div id ="radio-btn">
		   <%= f.input :style, :collection => ["Default", "Black Opaque", "Black Translucent", "Custom Color"], :as => :radio %>


			<%= f.submit "Next", :id => "next" %>
   			 <%#= f.submit %>
			</div>
			</div>


		</div>


  </div>
  <% end %>

  <script type="text/javascript">
  $(document).ready(function(){
    $('#master').sectionnavigator();
  });
  </script>


	<script type="text/javascript">        
	  $(document).ready(function()
	    {
	$('.input-append ').colorpicker()
	    });
	</script>

app/views/applications/_naming_step.html.erb
<div class="ContentsForm">
	
	<h4>App Property :: Device Selection</h4>
		<p> Choose the device type/s on which you want to run your application </p> </br>

		<div class="actionform">
	<p>Select the device on which you want to run your application</p>
	  <img src="/assets/phone.jpg" width="140" height="200">
      <img src="/assets/phone.jpg" width="140" height="200">
      <img src="/assets/phone.jpg" width="140" height="200"></br>
   <%= f.hidden_field :project_manager_id, :value => @application.project_manager_id %>
   <%= f.input :device_type, :label => '', :collection => ["Phone", "Tablet", "Both"], :as => :radio, :set_default => :Phone %>
   </div>
</div>
<%#= f.radio_button :device_type, %> 
    <%#= f.radio_button :device_type, false %> 

app/views/applications/_page_step.html.erb
<div class="ContentsForm">
<h4>Page Style:: Tab-Based </h4>
Using these properties one can define how the pages wood look and feel in the mobile

<h4>Page Control :</h4>
	<%= f.input :orientation, :label => '', :collection => ["Portrait", "Upside Down", "Landscape left", "Landscape Right"], :set_default => "Portrait"%>
	<%#= f.collection_check_boxes :options, [[true, 'Yes'] ,[false, 'No']], :Portrait, :last %>
	<h4>Tab Property</h4>
	Tint :

	<div class="input-append color" data-color="rgb(255, 146, 180)" data-color-format="rgb" id="cp3">
				<input type="hidden"  value="" readonly="" name = "application[tab_color]" >
				<span class="add-on"><i style="background-color: rgb(255, 146, 180);"></i></span>
          </div>
	<div id= "sidebar-property">
	<h4>Navigation Property</h4>
	Tint :

	<div class="input-append color" data-color="rgb(255, 146, 180)" data-color-format="rgb" id="cp3">
				<input type="hidden"  value="" readonly="" name = "application[navigation_color]" >
				<span class="add-on"><i style="background-color: rgb(255, 146, 180);"></i></span>
          </div>
          
   <%= f.input :style, :collection => ["Default", "Black Opaque", "Black Translucent", "Custom Color"], :as => :radio %>
	</div>
	</div>
</div>
<%= f.submit  %>


<script type="text/javascript">        
  $(document).ready(function()
    {
$('.input-append ').colorpicker()
    });
</script>

app/views/applications/_setting_step.html.erb
<div class="ContentsForm">
  <h4>App Property :: Device Selection</h4>
    <p> Choose the device type/s on which you want to run your application </p>
  <div class ="">
  <p>Select the device on which you want to run your application</p>
  <%= f.input :application_name %>
  <%= f.input :version %>
  <h4> App Navigation Structure </h4>
  	  <img src="/assets/phone.jpg" width="160" height="200">
          <img src="/assets/phone.jpg" width="160" height="200">
          <img src="/assets/phone.jpg" width="160" height="200"></br>


    <div id="radio-btn">
   <%= f.input :application_type, :label => '', :collection => ["Navi-Based","Tab-Based","View-Based"], :as => :radio, :set_default => "Navi-Based" %>
 </div>
</div>
		<div class= "sidebar">
            Supported orientation</br></br>
            
          <img src="/assets/phone.jpg" width="40" height="60"></br></br>
          <img src="/assets/phone.jpg" width="40" height="60"></br></br>
          <img src="/assets/phone.jpg" width="40" height="60"></br></br>
          <img src="/assets/phone.jpg" width="40" height="60"></br>
          <div id="radio-vertical">
            <%= f.input :orientation, :label => '', :collection => ["Portrait", "Upside Down", "Landscape left", "Landscape Right"], :as => :radio, :set_default => "Portrait" %>
          </div>
        </div>
        </div>

app/views/applications/edit.html.erb
<%= render "form"%>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>Application name</th>
    <th>Version</th>
    <th>Type</th>
    <th>Device type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  

<% @applications.each do |application| %>
  <tr>
    <td><%#= application.title %></td>
    <td><%= application.version %></td>
    <td><%#= application.type %></td>
    <td><%= application.device_type %></td>
    <td><%= application.application_name %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<div class="ContentsForm">
	

	<%= render 'form' %>
	
</div>

<%#= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<%= simple_form_for @application do |f| %>
<div class = "page-content">
<h3> App Manager </h3>
<p> The App Manager allows you to interact with certain components that may be required while building a mobile application.
	<div class = "content-text">
	<div id="text">
		<div id="icon">
		<img src="/assets/pages.gif" >
		</div>
		<div id="text-content">
		<h6> Page Manager </h6>
		<p> Where you can Add,Remove and Edit Pages in the App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/resource.jpeg" >
		</div>
		<div id="text-content">
		<h6> Resource Manager </h6>
		<p> Where you can Add,Remove and Edit images,videos and sounds of the App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/ldb.jpeg" >
		</div>
		<div id="text-content">
		<h6> Local Database </h6>
		<p> Where you can Add,Remove and Edit local database of the App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/rdb.jpg" >
		</div>
		<div id="text-content">
		<h6> Remote Database </h6>
		<p> Where you can Add,Remove and Edit remote database of the App</p>
		</div>
	</div></br>

	<div class="content-text2">
	<div id="text">
		<div id="icon">
		<img src="/assets/services.jpeg" >
		</div>
		<div id="text-content">
		<h6> Service </h6>
		<p> Where you can Add,Remove and Edit services of your App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/location.jpg" >
		</div>
		<div id="text-content">
		<h6> Location </h6>
		<p> Where you can Add,Remove and Edit location based-services of the App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/local.jpeg" >
		</div>
		<div id="text-content">
		<h6> Localisation </h6>
		<p> Where you can Add,Remove and Edit localization properties of the App</p>
		</div>
	</div></br>

	<div id="text">
		<div id="icon">
		<img src="/assets/app_prop.jpeg" >
		</div>
		<div id="text-content">
		<h6><%= link_to 'Application Property', edit_application_path  %></h6>
		
		<p> Edit Globalization Setting for your App</p>
		</div>
	</div>
</div>
</div>
<% end %>
</div>


<%#= link_to 'Edit', edit_application_path(@application) %> 
<%#= link_to 'Back', applications_path %>